# Default configuration for SandCore
# Customize these settings as needed

# General settings
setting1: value1
setting2: value2

# Example: Debug mode (true to enable verbose logging)
debug: true

# General plugin configuration for SandCore

# Leveling system settings:
#
# xpRequirements: A list where each entry represents the cumulative XP required to reach that level.
# For example, in the list below:
#   Level 0: 0 XP
#   Level 1: 100 XP
#   Level 2: 300 XP
#   Level 3: 600 XP
#   Level 4: 1000 XP
#   Level 5: 1500 XP
#   Level 6: 2100 XP
# maxLevel: The highest level a player can reach.
xpRequirements:
  - 0
  - 100
  - 300
  - 600
  - 1000
  - 1500
  - 2100
maxLevel: 6

# Other plugin settings can be added below.

levelUp:
  sound: "ENTITY_PLAYER_LEVELUP"
  message: "<hex:#00FF00>Congratulations, you have reached level {level}!" 

casting:
  feedback:
    enterMessage: "<hex:#00FF00>You have entered casting mode!"
    exitMessage: "<hex:#FF0000>You have exited casting mode."
    invalidCombo: "<hex:#FF0000>Invalid casting combo: {combo}"
    insufficientLevel: "<hex:#FF0000>You must be at least level {minLevel} to cast {skill}."
    castMessage: "<hex:#00FFFF>Casting spell: {skill}!"
  sounds:
    enter: "BLOCK_NOTE_BLOCK_PLING"
    exit: "BLOCK_NOTE_BLOCK_BASS"
    cast: "ENTITY_ENDER_DRAGON_GROWL"