# Default configuration for SandCore
# Customize these settings as needed

# General settings
setting1: value1
setting2: value2

debug: true

xpRequirements:
  - 0
  - 100
  - 300
  - 600
  - 1000
  - 1500
  - 2100
  - 8000
maxLevel: 7

levelUp:
  sound: "ENTITY_PLAYER_LEVELUP"
  message: "<hex:#00FF00>Congratulations, you have reached level {level}!"

casting:
  feedback:
    enterMessage: "<hex:#00FF00>You have entered casting mode!"
    exitMessage: "<hex:#FF0000>You have exited casting mode."
    invalidCombo: "<hex:#FF0000>Invalid casting combo: {combo}"
    insufficientLevel: "<hex:#FF0000>You must be at least level {minLevel} to cast {skill}."
    castMessage: "<hex:#00FFFF>Casting spell: {skill}!"
  sounds:
    enter: "BLOCK_NOTE_BLOCK_PLING"
    exit: "BLOCK_NOTE_BLOCK_BASS"
    cast: "ENTITY_ENDER_DRAGON_GROWL"

# STAT SYSTEM CONFIG
attributes:
  primary:
    strength:
      base: 5
      per-level: 1.2
      description: "Increases physical damage"
    dexterity:
      base: 5
      per-level: 1.1
      description: "Improves attack speed and accuracy"
    intelligence:
      base: 5
      per-level: 1.3
      description: "Boosts magical power"
    vitality:
      base: 5
      per-level: 1.0
      description: "Increases health pool"

  secondary:
    max_health:
      formula: "vitality * 10 + strength * 2"
    physical_damage:
      formula: "strength * 1.5 + dexterity * 0.5"
    attack_speed:
      formula: "dexterity * 0.1"
    critical_chance:
      formula: "dexterity * 0.2"
    critical_damage:
      formula: "150 + (dexterity * 0.5)"
    magic_resistance:
      formula: "intelligence * 0.8"
    physical_defense:
      formula: "vitality * 0.7 + strength * 0.3"

# DAMAGE SYSTEM CONFIG
damage:
  formulas:
    physical:
      base: "(physical_damage) * (1 + attack_speed/100)"
      critical: "critical_damage/100 + 1"
    magical: 
      base: "intelligence * 2.5"
      critical: "critical_damage/100 + 1.5"
  defense:
    physical: "physical_defense / (physical_defense + 100)"
    magical: "magic_resistance / (magic_resistance + 100)"
  penetration:
    physical: "physical_pen * 0.6"
    magical: "magic_pen * 0.4"
  options:
    min_damage: 1.0
    max_critical: 300.0

statistics:
  points-per-level: 2
  max-allocated: 50 # Maximum points per stat