name: SandCore
main: com.sandcore.SandCore
version: 1.0.0
description: A Minecraft MMORPG Plugin - SandCore
author: Sandman
api-version: 1.13
softdepend: [MythicMobs]

commands:
  reload:
    description: "Reloads the plugin configuration and refreshes all GUIs."
    usage: "/reload"
  classes:
    description: "Opens the class selection GUI."
    usage: "/classes"
  classinfo:
    description: "Displays your current class or another player's class."
    usage: "/classinfo [player]"
  givexp:
    description: "Give XP to a player."
    usage: "/givexp <player> <amount>"
  setlevel:
    description: "Set a player's level."
    usage: "/setlevel <player> <level>"
  debugxp:
    description: "Debug and test the XP/level system. Usage: /debugxp [player] [xpAmount]"
    usage: "/debugxp [player] [xpAmount]"
  profile:
    description: "Opens your profile GUI displaying your selected class, level, and XP."
    usage: "/profile"
  sandmmo:
    description: Main command for SandMMO
    usage: /sandmmo [reload|help|item]
    permission: sandmmo.command
    permission-message: You don't have permission!

permissions:
  sandmmo.admin.reload:
    description: "Allows the user to reload the plugin."
    default: op
  sandmmo.admin.classinfo:
    description: "Allows the user to view other players' classes."
    default: op
  sandmmo.command.item.give:
    description: Allows giving custom items
    default: op
  sandmmo.command.reload:
    description: Allows reloading plugin configs
    default: op
